### PR TITLE
Renamed some items, streamlined processing for display colors, revised tootip info.

### PR DESCRIPTION
**Pull request by brian-courts**
The tooltip info in this revision includes all the filing actions in the solution set, in a condensed format.

### CODE REVIEW

**Comment by MikePiper** [comment]
This pull request is showing no files changed again. (As of right now, it is showing me that the only included commit is yours from 6 days ago, merging the changes that I had made to remove some variables.)

I can't tell if this is something I'm doing wrong on my end (e.g., looking at the wrong thing) or if there's an additional step that needs to happen on your end.

**Comment by MikePiper** [comment]
My wife has some more experience with GitHub than I do. She said that a common mistake is to make the pull request from the remote branch (i.e., your branch on GitHub) without yet having done a push of your latest code from your local to your remote. Maybe that is what happened?

**Comment by brian-courts** [comment]
That is what happened - I hadn't pushed to the remote. I did that, and found one merge conflict (in the constructor in range.component.ts). I resolved that conflict. This pull request is now showing 4 files with changes. They should merge automatically.

**Comment by MikePiper** [comment]
Yep, the merge went fine just now. Thanks!

Regarding the tooltip, great idea to tap into the solutionsArray message field and just replace part of the text with a more succinct version. That way it still benefits from all the existing logic in solutionset.service.

**Pull request merged**
