### PR TITLE
Added method to switch display between cut and no-cut output.

### PR DESCRIPTION
**Pull request by brian-courts**
Your latest commit (using functions in solutionset.service to create strings related to the selected filling date(s), which are then used to populate an unordered list.) is very helpful. I had started developing the features included in this commit, and git was able to merge the files, each with their own changes, without many conflicts.
This is the first stage of an attempt to clarify to the user the results of choosing to consider a possible future cut in benefits. One thing I hope the user will notice is that, in many cases, a filing strategy that is good for the no-cut condition is also good for the cut condition. The actual present value is, of course, significantly different, but the percentage of maximum is often quite similar.

### CODE REVIEW

**Comment by MikePiper** [comment]
Hmm. This is showing for me as no files changed. (With your prior two pull requests I could click the "files changed" tab and see line-by-line differences in any files that had been edited.)

**Comment by brian-courts** [comment]
When I look at pull request #16, I see 4 files changed, with several changes in each of the files. I'll be away from my computer for a few hours. I'll check again when I get back.

**Comment by MikePiper** [comment]
Ah! As of now I see a new push, with four files changed. I'll take a look this afternoon.

**Comment by MikePiper** [comment]
I spent the afternoon testing it out and reading through the code. I like the radio buttons! Very clever.

I just made a commit that (I think) simplifies how the strings are generated, by just tapping into the scenario object.

I think it could allow for some code to be deleted, but I'm going to post that (and some similar ideas) in a new "issue."

**Pull request merged**
